extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:5318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:1234"
  awsxray:
    aws_log_groups: ["loan-broker-1", "loan-broker-2"]
  otlphttp:
    endpoint: "http://jaeger:4318"
  awsemf:
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus,awsemf]
    traces:
      receivers: [otlp]
      exporters: [awsxray,otlphttp]
