global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'NServiceBus Telemetry'
    scrape_interval: 1s
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'loanBroker:9464'
        - 'client:9464'
        - 'bank1:9464'
        - 'bank2:9464'
        - 'bank3:9464'
