{
 "title": "Loan Broker Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Quote average processing time by bank",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(loan_broker_bank_id) (increase(loan_broker_bank_processing_time_seconds_sum[1m])) / avg by(loan_broker_bank_id) (increase(loan_broker_bank_processing_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing Time by MessageType",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "avg by(nservicebus_message_type) (increase(nservicebus_messaging_processing_time_seconds_sum[1m])) / avg by(nservicebus_message_type) (increase(nservicebus_messaging_processing_time_seconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure rate by MessageType",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(avg by(nservicebus_message_type) (increase(nservicebus_messaging_failures_total[1m])) * 100) / avg by(nservicebus_message_type) (increase(nservicebus_messaging_fetches_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fetched messages rate per service over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 11, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum by(nservicebus_queue) (increase(nservicebus_messaging_fetches_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}