{
 "title": "LoanBroker",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Critical vs Processing vs Handling time per Loan Broker application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(increase(nservicebus_messaging_handlerTime_milliseconds_sum{nservicebus_queue=\"LoanBroker\"}[1m])) / avg(increase(nservicebus_messaging_handlerTime_milliseconds_count{nservicebus_queue=\"LoanBroker\"}[1m]))",
     "legendFormat": "Handling time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_processingtime_milliseconds_sum{nservicebus_queue=\"LoanBroker\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"LoanBroker\"}[1m]))",
     "legendFormat": "Processing time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_criticaltime_milliseconds_sum{nservicebus_queue=\"LoanBroker\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"LoanBroker\"}[1m]))",
     "legendFormat": "Critical time"
    }
   ]
  },
  {
   "title": "Critical vs Processing vs Handling time per Client application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(increase(nservicebus_messaging_handlerTime_milliseconds_sum{nservicebus_queue=\"Client\"}[1m])) / avg(increase(nservicebus_messaging_handlerTime_milliseconds_count{nservicebus_queue=\"Client\"}[1m]))",
     "legendFormat": "Handling time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_processingtime_milliseconds_sum{nservicebus_queue=\"Client\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Client\"}[1m]))",
     "legendFormat": "Processing time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_criticaltime_milliseconds_sum{nservicebus_queue=\"Client\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Client\"}[1m]))",
     "legendFormat": "Critical time"
    }
   ]
  },
  {
   "title": "Critical vs Processing vs Handling time per Bank1 adapter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(increase(nservicebus_messaging_handlerTime_milliseconds_sum{nservicebus_queue=\"Bank1Adapter\"}[1m])) / avg(increase(nservicebus_messaging_handlerTime_milliseconds_count{nservicebus_queue=\"Bank1Adapter\"}[1m]))",
     "legendFormat": "Handling time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_processingtime_milliseconds_sum{nservicebus_queue=\"Bank1Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank1Adapter\"}[1m]))",
     "legendFormat": "Processing time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_criticaltime_milliseconds_sum{nservicebus_queue=\"Bank1Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank1Adapter\"}[1m]))",
     "legendFormat": "Critical time"
    }
   ]
  },
  {
   "title": "Critical vs Processing vs Handling time per Bank2 adapter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(increase(nservicebus_messaging_handlerTime_milliseconds_sum{nservicebus_queue=\"Bank2Adapter\"}[1m])) / avg(increase(nservicebus_messaging_handlerTime_milliseconds_count{nservicebus_queue=\"Bank2Adapter\"}[1m]))",
     "legendFormat": "Handling time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_processingtime_milliseconds_sum{nservicebus_queue=\"Bank2Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank2Adapter\"}[1m]))",
     "legendFormat": "Processing time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_criticaltime_milliseconds_sum{nservicebus_queue=\"Bank2Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank2Adapter\"}[1m]))",
     "legendFormat": "Critical time"
    }
   ]
  },
  {
   "title": "Critical vs Processing vs Handling time per Bank3 adapter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(increase(nservicebus_messaging_handlerTime_milliseconds_sum{nservicebus_queue=\"Bank3Adapter\"}[1m])) / avg(increase(nservicebus_messaging_handlerTime_milliseconds_count{nservicebus_queue=\"Bank3Adapter\"}[1m]))",
     "legendFormat": "Handling time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_processingtime_milliseconds_sum{nservicebus_queue=\"Bank3Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank3Adapter\"}[1m]))",
     "legendFormat": "Processing time"
    },
    {
     "expr": "avg(increase(nservicebus_messaging_criticaltime_milliseconds_sum{nservicebus_queue=\"Bank3Adapter\"}[1m])) / avg(increase(nservicebus_messaging_criticaltime_milliseconds_count{nservicebus_queue=\"Bank3Adapter\"}[1m]))",
     "legendFormat": "Critical time"
    }
   ]
  },
  {
   "title": "Quote average processing time by bank",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg by(loan_broker_bank_id) (increase(loan_broker_bank_processing_time_milliseconds_sum[1m])) / avg by(loan_broker_bank_id) (increase(loan_broker_bank_processing_time_milliseconds_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}