version: "3.3"
name: "aws-loan-broker"
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sns,sqs,iam,s3,dynamodb
      - DEBUG=1
      - HOSTNAME=localstack
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
      - "8000:5000"
  loanBroker:
    image: loanbroker
    network_mode: service:localstack
  bank1:
    image: bank1adapter
    network_mode: service:localstack
  bank2:
    image: bank2adapter
    network_mode: service:localstack
  bank3:
    image: bank3adapter
    network_mode: service:localstack
  client:
    image: client
    network_mode: service:localstack
    tty: true
    stdin_open: true
    command: sh