services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sns,sqs,iam,s3,dynamodb
      - DEBUG=1
      - HOSTNAME=localstack
      - EDGE_PORT=4566
    ports:
      - '4566-4597:4566-4597'
      - "8000:5000"
  loan-broker:
    build:
      context: ./
      dockerfile: ./LoanBroker/Dockerfile
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - OTLP_METRICS_URL=http://adot:5318/v1/metrics
      - OTLP_TRACING_URL=http://jaeger:4318/v1/traces
  bank1:
    build:
      context: ./
      dockerfile: ./Bank1Adapter/Dockerfile
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - OTLP_METRICS_URL=http://adot:5318/v1/metrics
      - OTLP_TRACING_URL=http://jaeger:4318/v1/traces
  bank2:
    build:
      context: ./
      dockerfile: ./Bank2Adapter/Dockerfile
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - OTLP_METRICS_URL=http://adot:5318/v1/metrics
      - OTLP_TRACING_URL=http://jaeger:4318/v1/traces
  bank3:
    build:
      context: ./
      dockerfile: ./Bank3Adapter/Dockerfile
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - OTLP_METRICS_URL=http://adot:5318/v1/metrics
      - OTLP_TRACING_URL=http://jaeger:4318/v1/traces
  client:
    build:
      context: ./
      dockerfile: ./Client/Dockerfile
    environment:
      - LOCALSTACK_URL=http://localstack:4566
      - OTLP_METRICS_URL=http://adot:5318/v1/metrics
      - OTLP_TRACING_URL=http://jaeger:4318/v1/traces
    tty: true
    stdin_open: true
    command: sh
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
      - ./data-prometheus:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./data-grafana:/var/lib/grafana
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 16686:16686
      - 4318:4318
      - 9411:9411
      - 14250
  adot:
    image: amazon/aws-otel-collector
    command: [ "--config=/etc/otel-agent-config.yaml" ]
    ports:
      - "13133:13133"     # adot health_check
      - "5318:5318"       # adot
      - "1234:1234"       # adot
    volumes:
      - ./adot/config.yaml:/etc/otel-agent-config.yaml
